#!/bin/env python3# autogenerated by meta_data.py
/g/g0/defazio1/non-jira-projects/migration/meta_data.py m d t _ s e t u p c o u n t c r e a t e n e w _ f i l e s f i l e s _ d i r n u m _ p r o c s n u m _ n o d e s s e t u p
